name: Run Update Paper Links Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

env:
  GITHUB_USER_NAME: nlp-arxiv-daily-bot
  GITHUB_USER_EMAIL: nlp-arxiv-daily-bot@gmail.com

jobs:
  build:
    name: update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: make set-dev

      - name: Run daily arxiv
        run: uv run --frozen python daily_arxiv.py --update_paper_links

      - name: Push new nlp-arxiv-daily.md
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Github Action Automatic Update nlp Arxiv Papers"
          files: README.md docs/nlp-arxiv-daily.json docs/nlp-arxiv-daily-web.json docs/index.md
          rebase: "true"
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
